BehaviorDesignPattern.StrategyPattern/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using BaseProject.WebUI.Models;
using BehaviorDesignPattern.StrategyPattern.Models.Entity;
using BehaviorDesignPattern.StrategyPattern.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace BehaviorDesignPattern.StrategyPattern.Controllers
{
    [Authorize]
    public class ProductController : Controller
    {
        private readonly IProductRepository _context;
        private readonly UserManager<AppUser> _userManager;
        

        public ProductController(IProductRepository context, UserManager<AppUser> userManager)
        {
            _context = context;
            _userManager = userManager;
            
        }


        // GET: Product
        public async Task<IActionResult> Index()
        {
            var user = _userManager.FindByNameAsync(User.Identity.Name).Result;
            
            var repositoryType = _context.GetType().Name;
            
            ViewData["RepositoryType"] = repositoryType;
            
            return View(await _context.GetAllByUserId(user.Id));
        }

        // GET: Product/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null 
                ||string.IsNullOrEmpty(id))
            {
                return NotFound();
            }

            var product = await _context.GetById(id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // GET: Product/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Product/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Price,Stock,UserId,CreatedDate")] Product product)
        {
            if (ModelState.IsValid)
            {
                await  _context.Add(product);
                return RedirectToAction(nameof(Index));
            }

            product.CreatedDate = DateTime.Now;
            product.UserId = _userManager.FindByNameAsync(User.Identity.Name).Result.Id;
            await _context.Add(product: product);
            return RedirectToAction(nameof(Index));
        }

        // GET: Product/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.GetById(id);
            if (product == null)
            {
                return NotFound();
            }
            await _context.Update(product);
            return View(product);
        }

        // POST: Product/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Id,Name,Price,Stock,UserId,CreatedDate")] Product product)
        {
            if (id != product.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _context.Update(product);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (! await ProductExists(product.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(product);
        }

        // GET: Product/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.GetById(id);
            if (product == null)
            {
                return NotFound();
            }
            return View(product);
        }

        // POST: Product/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var product = await _context.GetById(id);
            if (product != null)
            {
                _context.Delete(product);
            }
            return RedirectToAction(nameof(Index));
        }

        private async Task<bool> ProductExists(string id)
        {
            var product = await _context.GetById(id);
            return product != null;
        }
    }
}

BehaviorDesignPattern.StrategyPattern/Controllers/SettingsController.cs
using System.Security.Claims;
using BaseProject.WebUI.Models;
using BehaviorDesignPattern.StrategyPattern.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace BehaviorDesignPattern.StrategyPattern.Controllers
{
    [Authorize]
    public class SettingsController : Controller
    {
        private readonly UserManager<AppUser> _userManager;
        private readonly SignInManager<AppUser> _signInManager;

        public SettingsController(UserManager<AppUser> userManager, SignInManager<AppUser> signInManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
        }

        // GET: SettingsController
        public ActionResult Index()
        {
            Settings settings = new();
            if (User.Claims.Where(x=>x.Type== Settings.claimDatabaseType).FirstOrDefault()!= null)
            {
                settings.DatabaseType = (DatabaseType)int.Parse(User.Claims.Where(x => x.Type == Settings.claimDatabaseType).FirstOrDefault().Value);
            }
            else
            {
                settings.DatabaseType = settings.GetDefaultDatabaseType;
            }
            return View(settings);
        }

        [HttpPost]
        public async Task<IActionResult> ChangeDatabase(Settings model)
        {
            var user = await _userManager.FindByNameAsync(User.Identity.Name);
            
            var newClaim = new Claim(Settings.claimDatabaseType, ((int)model.DatabaseType).ToString());
            
            var oldClaim = User.Claims.Where(x => x.Type == Settings.claimDatabaseType).FirstOrDefault();
            
            if (oldClaim != null)
            {
                await _userManager.ReplaceClaimAsync(user, oldClaim, newClaim);
            }
            else
            {
                await _userManager.AddClaimAsync(user, newClaim);
            }
            
            await _signInManager.SignOutAsync();


            var result =  await HttpContext.AuthenticateAsync();
            
            await _signInManager.SignInAsync(user, result.Properties);
            
            return RedirectToAction("Index");
        }
    }
}

BehaviorDesignPattern.StrategyPattern/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BaseProject.WebUI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BaseProject.WebUI.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">My App</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ml-auto">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item">
                            @* add form for logout  *@
                            <form class="form-inline" asp-controller="Account" asp-action="Logout" method="post">
                                <button type="submit" class="nav-link btn btn-link">Logout</button>
                            </form>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Settings" asp-action="Index">Settings</a>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Product" asp-action="Index">Products</a>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Account" asp-action="Login">Login</a>
                        </li>
                    }
                </ul>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - BaseProject.WebUI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>